// flow-typed signature: d51cacb0d0661646953b1448233acf6e
// flow-typed version: <<STUB>>/@personare/react-storybook-decorator-github-corner_v^0.1.5/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@personare/react-storybook-decorator-github-corner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@personare/react-storybook-decorator-github-corner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@personare/react-storybook-decorator-github-corner/build/index' {
  declare module.exports: any;
}

declare module '@personare/react-storybook-decorator-github-corner/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@personare/react-storybook-decorator-github-corner/build/index.js' {
  declare module.exports: $Exports<'@personare/react-storybook-decorator-github-corner/build/index'>;
}
declare module '@personare/react-storybook-decorator-github-corner/example/index.js' {
  declare module.exports: $Exports<'@personare/react-storybook-decorator-github-corner/example/index'>;
}
declare module '@personare/react-storybook-decorator-github-corner/index' {
  declare module.exports: $Exports<'@personare/react-storybook-decorator-github-corner'>;
}
declare module '@personare/react-storybook-decorator-github-corner/index.js' {
  declare module.exports: $Exports<'@personare/react-storybook-decorator-github-corner'>;
}
